apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dhanrajsr/spring-gitops.git
    targetRevision: main
    path: argocd              # ArgoCD watches this folder
                              # and creates all child apps inside it
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
