apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-apps-staging
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - list:
        elements:
          - app: spring-maven
          - app: spring-gradle

  template:
    metadata:
      name: "{{.app}}-staging"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/dhanrajsr/spring-gitops.git
        targetRevision: main
        path: "apps/{{.app}}/helm"
        helm:
          valueFiles:
            - values.yaml
            - values-staging.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
