image:
  repository: dhanrajsubbaianind/spring-maven-app
  tag: 0a0b1fdf4973bc5e0a5ee1590a42d56ff2dab85d
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  path: /api/health
  initialDelaySeconds: 90
  periodSeconds: 10

readinessProbe:
  path: /api/health
  initialDelaySeconds: 75
  periodSeconds: 5

ingress:
  host: spring-maven.devopscab.com
  previewHost: ""
  certificateArn: arn:aws:acm:us-east-1:497041484428:certificate/aeb50a3f-01af-4fbc-9165-45acde587dee

blueGreen:
  autoPromotionEnabled: false   # manual promotion required
  scaleDownDelaySeconds: 30     # keep old blue pods 30s after promotion — allows instant rollback
  previewReplicaCount: 1        # number of green pods to spin up for preview
  abortScaleDownDelaySeconds: 30  # scale down failed green pods 30s after abort
