image:
  repository: dhanrajsubbaianind/spring-maven-app
  tag: 49cbb1199484b14ca841b6d8f4d12af8632dddef
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  path: /api/health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /api/health
  initialDelaySeconds: 20
  periodSeconds: 5
